url: "http://www.jancylingliu.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Jancy Ling Liu" # the name of your site, e.g. ACME Corp.
description: "Assistant Professor of Economics, The College of Wooster"
plugins:
  - jekyll-sitemap