menu:
- {name: 'Research', url: '/research'}
- {name: 'Teaching', url: '/teaching'}
- {name: 'CV', url: '/cv'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
#- {icon: 'envelope', link: 'mailto: jancyll@gatech.edu'}
#- {icon: 'github', link: 'https://github.com/Jancyll'}
#- {icon: 'twitter', link: 'https://twitter.com/econ_ling'}
#- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jancy-ling-liu-2018416a/'}
- {icon: 'envelope', link: 'mailto: jancyll@gatech.edu', prefix: 'fas'}
- {icon: 'github', link: 'https://github.com/Jancyll', prefix: 'fab'}
- {icon: 'twitter', link: 'https://twitter.com/econ_ling', prefix: 'fab'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jancy-ling-liu-2018416a/', prefix: 'fab'}

contacts:
- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
